task: detection

num_classes: 2
remap_mscoco_category: True

train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /home/hb/1_machine_vision/Parking_detection/data/archive_coco/dataset/output/train
    ann_file: /home/hb/1_machine_vision/Parking_detection/data/archive_coco/dataset/output/train.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 2
  num_workers: 4
  drop_last: True 


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /home/hb/1_machine_vision/Parking_detection/data/archive_coco/dataset/output/val
    ann_file: /home/hb/1_machine_vision/Parking_detection/data/archive_coco/dataset/output/val.json
    transforms:
      type: Compose
      ops: ~ 

  shuffle: False
  batch_size: 2
  num_workers: 4
  drop_last: False
  
  
  
  
